# -----------  Agents  -----------

[[agents]]
id = "test_agent4"
name = "Agent 4"
public_address = "HcSCjhqYOqc7u3uwybCm3f8ze934wzQywhYfjnbyWfuyp6xnqk58VTbM5obhujr"
keystore_file = "./agent4.keystore"

# -----------  DNAs  -----------
[[dnas]]
  id = "personas_profiles"
  file = "../personas-profiles/dna/personas-profiles-agent4.dna.json"
  hash = "Qmdt8yw5py8x2q7CZ5NsLuj61NjfLGjQiYz55LNjCTtCzs"
[[dnas]]
  id = "deep_key"
  file = "../DeepKey/dna/deepkey.dna.json"
  hash = "Qmavj2zmA2EyWyq9RS11Zz3FGcxiWXrcLd8onYiCHPpXoL"
[[dnas]]
  id = "chat_dna"
  file = "./dna/holochain-basic-chat.dna.json"
  hash = "Qmat3Lk9Fb1x4pGMZRcm9vGcWQtFn6YcWUoYEr7VRk4cTz"

[[instances]]
  id = "dpki_happ"
  dna = "deep_key"
  agent = "test_agent4"
[instances.storage]
  type = "memory"
[[instances]]
  id = "personas-profiles"
  dna = "personas_profiles"
  agent = "test_agent4"
[instances.storage]
  type = "memory"
[[instances]]
  id = "holo-chat"
  dna = "chat_dna"
  agent = "test_agent4"
[instances.storage]
  type = "memory"

[[bridges]]
  caller_id = "holo-chat"
  callee_id = "personas-profiles"
  handle = "p-p-bridge"

[[interfaces]]
  id = "websocket_interface"
[interfaces.driver]
  type = "websocket"
  port = 3404
[[interfaces.instances]]
  id = "dpki_happ"
[[interfaces.instances]]
  id = "holo-chat"
[[interfaces.instances]]
  id = "personas-profiles"

# -----------  Networking  -----------

[network]
type = "n3h"
n3h_mode = "REAL"
n3h_persistence_path = "./n3h-agent4"
n3h_log_level = "i"
bootstrap_nodes = []
