# -----------  Agents  -----------


[[agents]]
id = "test_agent2"
name = "Agent 2"
public_address = "HcSCIUKodbWktcbmwyAaVrYnsbadi6b9sOV9D4ZoE8i333ZtcGw38Jn3U6u63qi"
keystore_file = "./agent2.keystore"

# [[agents]]
# id = "AgentID update the agent property in [[instances]]"
# name = "Your agent name here"
# public_address = "public addess"
# keystore_file = "path/to/keystore"
# -----------  DNA  -----------


[[dnas]]
id = "chat_dna"
file = "./dna/holochain-basic-chat.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "holo-chat"
dna = "chat_dna"
agent = "test_agent2"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage-agent2"


[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3402
[[interfaces.instances]]
id = "holo-chat"

[[interfaces]]
id = "http_interface"
[interfaces.driver]
type = "http"
port = 4002
[[interfaces.instances]]
id = "holo-chat"

# -----------  UI  -----------

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3002
dna_interface = "websocket_interface"

# -----------  Networking  -----------

[network]
n3h_persistence_path = "/Users/philipbeadle/holochain/Holochain/n3h-agent2"
n3h_log_level = "i"
bootstrap_nodes = ["wss://10.1.1.202:59338/?a=HcSCjS9KX88Tfesg9pFPK5D9duP6axitnb8f6VKPIvidwx6sHKPZcMh34Ztf7ya"]
